# Generated by Django 3.0.6 on 2020-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Artist', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
