# Generated by Django 3.0.6 on 2020-05-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
    ]
