# Generated by Django 3.0.6 on 2020-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200602_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
